services:
  - type: web
    name: buddy-ai
    env: python
    buildCommand: pip install -r "Backend code/requirements.txt"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GEMINI_API_KEY
        sync: false
